### ISSUE TITLE
Ytelseproblemer med  dp-regel-api

### ISSUE THREAD

**Issue by geiralund** [navikt/dp-regel-api#85]
Noe™ låser ressurser i dp-regel-api som fører til at apiet tas ned. Vi mistenker at KafkaSubsumsjonBruktConsumer og dp-datalaster-subsumsjonbrukt er med på dette, så disse er midlertidig skrudd av (i https://github.com/navikt/dp-regel-api/commit/578c1021b76df90acf66fd2e9e94fc3b58745d37) 

KafkaSubsumsjonBruktConsumer i dp-regel-api lytter på `privat-dagpenger-subsumsjon-brukt` og markerer subsumsjonid for brukt, samtidig 
lytter  dp-datalaster-subsumsjonbrukt på `privat-dagpenger-subsumsjon-brukt` for å hente data gitt subsumsjonid 
![Screenshot 2020-04-03 at 15 55 48](https://user-images.githubusercontent.com/219278/78368322-bd1ba700-75c3-11ea-9b7a-8566fb9b7b66.png)

Ser også lange transaksjontider i databasen. 

![Screenshot 2020-04-03 at 15 59 49](https://user-images.githubusercontent.com/219278/78368740-5fd42580-75c4-11ea-885a-cda88068569e.png)
som gikk ned etter at vi skrudde av dp-datalaster-subsumsjonbrukt

**Comment by geiralund** [comment]
Skrudde av vaktmestere i dp-regel-api og dp-inntekt-api til vi har kontroll

**Comment by geiralund** [comment]
Mulig vi må se på db spørringer i 

https://github.com/navikt/dp-regel-api/blob/master/src/main/kotlin/no/nav/dagpenger/regel/api/db/PostgresSubsumsjonStore.kt#L202-L208 
Det skal være indekser på de, men blir ikke truffet? 

```
CREATE INDEX minsteinntektresultat_idx ON v2_subsumsjon((data->'minsteInntektResultat' ->> 'subsumsjonsId'));
CREATE INDEX perioderesultat_idx ON v2_subsumsjon((data->'periodeResultat' ->> 'subsumsjonsId'));
CREATE INDEX satsresultat_idx ON v2_subsumsjon((data->'satsResultat' ->> 'subsumsjonsId'));
CREATE INDEX grunnlagresultat_idx ON v2_subsumsjon((data->'grunnlagResultat' ->> 'subsumsjonsId')
```

**Comment by androa** [comment]
Vi har jo bare tre databaseconnections så denne spørringa spiser jo fort opp alle tre og blokkerer stort sett all annen aktivitet.

**Comment by geiralund** [comment]
Skal vi også doble connnections @androa @gtcno ?

**Comment by androa** [comment]
Det er jo en ganske sentral tjeneste i riggen vår i dag, så det burde være rom for å argumentere for at vi trenger mer enn de 3 "vanlige" connectionene.

**Comment by geiralund** [comment]
Bumpa til 5 connections. Og startet consumeren igjen, og skrudde av :) 

Må også refaktorere https://github.com/navikt/dp-regel-api/blob/fa95df4ae39b83c197f352d53ab2a2f3c24db22f/src/main/kotlin/no/nav/dagpenger/regel/api/Vaktmester.kt#L55-L66

**Comment by androa** [comment]
> Og startet consumeren igjen, og skrudde av :)

Hva skrudde du av? :D

**Comment by geiralund** [comment]
> Hva skrudde du av? :D

subsumsjon brukt consumer

Skrudde på igjen nå

**Comment by androa** [comment]
Oi, jeg closa den jeg. Litt med et uhell. Men den er vel egentlig løst?

**Comment by geiralund** [comment]
jepp, den er ferdig
